/**
 * Sanlam Allianz country lookup (from GET /api/… country lookup), baked in so
 * the destination selector loads instantly and names map to the CountryId the
 * quote/booking API expects. Region drives pricing tier.
 * Regenerate from the live lookup if Allianz updates its list.
 */

export const ALLIANZ_REGIONS: Record<number, { name: string; description: string }> = {
  1: { name: "Schengen", description: "All Schengen States" },
  2: { name: "US_Canada_Japan", description: "Worldwide including all Schengen states" },
  3: { name: "Others", description: "Worldwide excluding USA, Canada & Japan" },
};

export interface AllianzCountry {
  /** CountryId sent to the quote/booking API. */
  id: number;
  name: string;
  /** ISO alpha-2 code. */
  alpha: string;
  /** RegionId — see ALLIANZ_REGIONS. */
  region: number;
}

export const ALLIANZ_COUNTRIES: readonly AllianzCountry[] = [
  { id: 114, name: "Afghanistan", alpha: "AF", region: 3 },
  { id: 116, name: "Albania", alpha: "AL", region: 3 },
  { id: 150, name: "Algeria", alpha: "DZ", region: 3 },
  { id: 113, name: "Andorra", alpha: "AD", region: 3 },
  { id: 118, name: "Angola", alpha: "AO", region: 3 },
  { id: 115, name: "Anguilla", alpha: "AI", region: 3 },
  { id: 175, name: "Antigua & Barbuda", alpha: "AG", region: 3 },
  { id: 119, name: "Argentina", alpha: "AR", region: 3 },
  { id: 117, name: "Armenia", alpha: "AM", region: 3 },
  { id: 120, name: "Australia", alpha: "AU", region: 3 },
  { id: 2, name: "Austria", alpha: "AT", region: 1 },
  { id: 121, name: "Azerbaijan", alpha: "AZ", region: 3 },
  { id: 132, name: "Bahamas", alpha: "BS", region: 3 },
  { id: 126, name: "Bahrain", alpha: "BH", region: 3 },
  { id: 123, name: "Bangladesh", alpha: "BD", region: 3 },
  { id: 122, name: "Barbados", alpha: "BB", region: 3 },
  { id: 135, name: "Belarus", alpha: "BY", region: 3 },
  { id: 3, name: "Belgium", alpha: "BE", region: 1 },
  { id: 136, name: "Belize", alpha: "BZ", region: 3 },
  { id: 128, name: "Benin", alpha: "BJ", region: 3 },
  { id: 129, name: "Bermuda", alpha: "BM", region: 3 },
  { id: 133, name: "Bhutan", alpha: "BT", region: 3 },
  { id: 176, name: "Bolivia", alpha: "BO", region: 3 },
  { id: 177, name: "Bosnia & Herzegovina", alpha: "BA", region: 3 },
  { id: 134, name: "Botswana", alpha: "BW", region: 3 },
  { id: 131, name: "Brazil", alpha: "BR", region: 3 },
  { id: 130, name: "Brunei Darussalam", alpha: "BN", region: 3 },
  { id: 125, name: "Bulgaria", alpha: "BG", region: 3 },
  { id: 124, name: "Burkina Faso", alpha: "BF", region: 3 },
  { id: 127, name: "Burundi", alpha: "BI", region: 3 },
  { id: 170, name: "Cambodia", alpha: "KH", region: 3 },
  { id: 140, name: "Cameroon", alpha: "CM", region: 3 },
  { id: 4, name: "Canada", alpha: "CA", region: 2 },
  { id: 145, name: "Cape Verde", alpha: "CV", region: 3 },
  { id: 172, name: "Cayman Islands", alpha: "KY", region: 3 },
  { id: 137, name: "Central African Republic", alpha: "CF", region: 3 },
  { id: 174, name: "Chad", alpha: "TD", region: 3 },
  { id: 139, name: "Chile", alpha: "CL", region: 3 },
  { id: 141, name: "China", alpha: "CN", region: 3 },
  { id: 142, name: "Colombia", alpha: "CO", region: 3 },
  { id: 171, name: "Comoros", alpha: "KM", region: 3 },
  { id: 138, name: "Congo", alpha: "CG", region: 3 },
  { id: 143, name: "Costa Rica", alpha: "CR", region: 3 },
  { id: 168, name: "Croatia", alpha: "HR", region: 3 },
  { id: 144, name: "Cuba", alpha: "CU", region: 3 },
  { id: 146, name: "Cyprus", alpha: "CY", region: 3 },
  { id: 6, name: "Czech Republic", alpha: "CZ", region: 1 },
  { id: 178, name: "Democratic Republic of the Congo", alpha: "CD", region: 3 },
  { id: 8, name: "Denmark", alpha: "DK", region: 1 },
  { id: 147, name: "Djibouti", alpha: "DJ", region: 3 },
  { id: 148, name: "Dominica", alpha: "DM", region: 3 },
  { id: 149, name: "Dominican Republic", alpha: "DO", region: 3 },
  { id: 151, name: "Ecuador", alpha: "EC", region: 3 },
  { id: 152, name: "Egypt", alpha: "EG", region: 3 },
  { id: 173, name: "El Salvador", alpha: "SV", region: 3 },
  { id: 164, name: "Equatorial Guinea", alpha: "GQ", region: 3 },
  { id: 153, name: "Eritrea", alpha: "ER", region: 3 },
  { id: 9, name: "Estonia", alpha: "EE", region: 1 },
  { id: 154, name: "Ethiopia", alpha: "ET", region: 3 },
  { id: 155, name: "Fiji", alpha: "FJ", region: 3 },
  { id: 11, name: "Finland", alpha: "FI", region: 1 },
  { id: 12, name: "France", alpha: "FR", region: 1 },
  { id: 159, name: "French Guiana", alpha: "GF", region: 3 },
  { id: 156, name: "Gabon", alpha: "GA", region: 3 },
  { id: 161, name: "Gambia", alpha: "GM", region: 3 },
  { id: 158, name: "Georgia", alpha: "GE", region: 3 },
  { id: 7, name: "Germany", alpha: "DE", region: 1 },
  { id: 160, name: "Ghana", alpha: "GH", region: 3 },
  { id: 179, name: "Great Britain", alpha: "GB", region: 3 },
  { id: 13, name: "Greece", alpha: "GR", region: 1 },
  { id: 157, name: "Grenada", alpha: "GD", region: 3 },
  { id: 163, name: "Guadeloupe", alpha: "GP", region: 3 },
  { id: 165, name: "Guatemala", alpha: "GT", region: 3 },
  { id: 162, name: "Guinea", alpha: "GN", region: 3 },
  { id: 166, name: "Guinea-Bissau", alpha: "GW", region: 3 },
  { id: 167, name: "Guyana", alpha: "GY", region: 3 },
  { id: 169, name: "Haiti", alpha: "HT", region: 3 },
  { id: 14, name: "Honduras", alpha: "HN", region: 3 },
  { id: 15, name: "Hungary", alpha: "HU", region: 1 },
  { id: 19, name: "Iceland", alpha: "IS", region: 1 },
  { id: 17, name: "India", alpha: "IN", region: 3 },
  { id: 16, name: "Indonesia", alpha: "ID", region: 3 },
  { id: 180, name: "Iran", alpha: "IR", region: 3 },
  { id: 18, name: "Iraq", alpha: "IQ", region: 3 },
  { id: 200, name: "Ireland", alpha: "IE", region: 3 },
  { id: 181, name: "Israel and the Occupied Territories", alpha: "IL", region: 3 },
  { id: 20, name: "Italy", alpha: "IT", region: 1 },
  { id: 182, name: "Ivory Coast (Cote d'Ivoire)", alpha: "CI", region: 3 },
  { id: 21, name: "Jamaica", alpha: "JM", region: 3 },
  { id: 23, name: "Japan", alpha: "JP", region: 2 },
  { id: 22, name: "Jordan", alpha: "JO", region: 3 },
  { id: 27, name: "Kazakhstan", alpha: "KZ", region: 3 },
  { id: 24, name: "Kenya", alpha: "KE", region: 3 },
  { id: 183, name: "Korea, Democratic Republic of (North Korea)", alpha: "KP", region: 3 },
  { id: 184, name: "Korea, Republic of (South Korea)", alpha: "KR", region: 3 },
  { id: 185, name: "Kosovo", alpha: "RS", region: 3 },
  { id: 26, name: "Kuwait", alpha: "KW", region: 3 },
  { id: 186, name: "Kyrgyz Republic (Kyrgyzstan)", alpha: "KG", region: 3 },
  { id: 187, name: "Laos", alpha: "LA", region: 3 },
  { id: 36, name: "Latvia", alpha: "LV", region: 1 },
  { id: 28, name: "Lebanon", alpha: "LB", region: 3 },
  { id: 33, name: "Lesotho", alpha: "LS", region: 3 },
  { id: 32, name: "Liberia", alpha: "LR", region: 3 },
  { id: 37, name: "Libya", alpha: "LY", region: 3 },
  { id: 30, name: "Liechtenstein", alpha: "LI", region: 1 },
  { id: 34, name: "Lithuania", alpha: "LT", region: 1 },
  { id: 35, name: "Luxembourg", alpha: "LU", region: 1 },
  { id: 42, name: "Madagascar", alpha: "MG", region: 3 },
  { id: 51, name: "Malawi", alpha: "MW", region: 3 },
  { id: 53, name: "Malaysia", alpha: "MY", region: 3 },
  { id: 50, name: "Maldives", alpha: "MV", region: 3 },
  { id: 43, name: "Mali", alpha: "ML", region: 3 },
  { id: 48, name: "Malta", alpha: "MT", region: 1 },
  { id: 45, name: "Martinique", alpha: "MQ", region: 3 },
  { id: 46, name: "Mauritania", alpha: "MR", region: 3 },
  { id: 49, name: "Mauritius", alpha: "MU", region: 3 },
  { id: 109, name: "Mayotte", alpha: "YT", region: 3 },
  { id: 52, name: "Mexico", alpha: "MX", region: 3 },
  { id: 40, name: "Moldova, Republic of", alpha: "MD", region: 3 },
  { id: 39, name: "Monaco", alpha: "MC", region: 3 },
  { id: 44, name: "Mongolia", alpha: "MN", region: 3 },
  { id: 41, name: "Montenegro", alpha: "ME", region: 3 },
  { id: 47, name: "Montserrat", alpha: "MS", region: 3 },
  { id: 38, name: "Morocco", alpha: "MA", region: 3 },
  { id: 54, name: "Mozambique", alpha: "MZ", region: 3 },
  { id: 188, name: "Myanmar/Burma", alpha: "MM", region: 3 },
  { id: 55, name: "Namibia", alpha: "NA", region: 3 },
  { id: 61, name: "Nepal", alpha: "NP", region: 3 },
  { id: 59, name: "Netherlands", alpha: "NL", region: 1 },
  { id: 62, name: "New Zealand", alpha: "NZ", region: 3 },
  { id: 58, name: "Nicaragua", alpha: "NI", region: 3 },
  { id: 56, name: "Niger", alpha: "NE", region: 3 },
  { id: 60, name: "Norway", alpha: "NO", region: 1 },
  { id: 63, name: "Oman", alpha: "OM", region: 3 },
  { id: 189, name: "Pacific Islands", alpha: "PC", region: 3 },
  { id: 68, name: "Pakistan", alpha: "PK", region: 3 },
  { id: 64, name: "Panama", alpha: "PA", region: 3 },
  { id: 66, name: "Papua New Guinea", alpha: "PG", region: 3 },
  { id: 72, name: "Paraguay", alpha: "PY", region: 3 },
  { id: 65, name: "Peru", alpha: "PE", region: 3 },
  { id: 67, name: "Philippines", alpha: "PH", region: 3 },
  { id: 69, name: "Poland", alpha: "PL", region: 1 },
  { id: 71, name: "Portugal", alpha: "PT", region: 1 },
  { id: 70, name: "Puerto Rico", alpha: "PR", region: 3 },
  { id: 73, name: "Qatar", alpha: "QA", region: 3 },
  { id: 190, name: "Republic of Macedonia", alpha: "MK", region: 3 },
  { id: 191, name: "Reunion", alpha: "RE", region: 3 },
  { id: 74, name: "Romania", alpha: "RO", region: 3 },
  { id: 76, name: "Russian Federation", alpha: "RU", region: 3 },
  { id: 77, name: "Rwanda", alpha: "RW", region: 3 },
  { id: 25, name: "Saint Kitts and Nevis", alpha: "KN", region: 3 },
  { id: 29, name: "Saint Lucia", alpha: "LC", region: 3 },
  { id: 192, name: "Saint Vincent's & Grenadines", alpha: "VC", region: 3 },
  { id: 107, name: "Samoa", alpha: "WS", region: 3 },
  { id: 91, name: "Sao Tome and Principe", alpha: "ST", region: 3 },
  { id: 78, name: "Saudi Arabia", alpha: "SA", region: 3 },
  { id: 87, name: "Senegal", alpha: "SN", region: 3 },
  { id: 75, name: "Serbia", alpha: "RS", region: 3 },
  { id: 80, name: "Seychelles", alpha: "SC", region: 3 },
  { id: 86, name: "Sierra Leone", alpha: "SL", region: 3 },
  { id: 83, name: "Singapore", alpha: "SG", region: 3 },
  { id: 193, name: "Slovak Republic (Slovakia)", alpha: "SK", region: 3 },
  { id: 85, name: "Slovakia", alpha: "SK", region: 1 },
  { id: 84, name: "Slovenia", alpha: "SI", region: 1 },
  { id: 79, name: "Solomon Islands", alpha: "SB", region: 3 },
  { id: 88, name: "Somalia", alpha: "SO", region: 3 },
  { id: 110, name: "South Africa", alpha: "ZA", region: 3 },
  { id: 90, name: "South Sudan", alpha: "SS", region: 3 },
  { id: 10, name: "Spain", alpha: "ES", region: 1 },
  { id: 31, name: "Sri Lanka", alpha: "LK", region: 3 },
  { id: 81, name: "Sudan", alpha: "SD", region: 3 },
  { id: 89, name: "Suriname", alpha: "SR", region: 3 },
  { id: 92, name: "Swaziland", alpha: "SZ", region: 3 },
  { id: 82, name: "Sweden", alpha: "SE", region: 1 },
  { id: 5, name: "Switzerland", alpha: "CH", region: 1 },
  { id: 194, name: "Syria", alpha: "SY", region: 3 },
  { id: 95, name: "Tajikistan", alpha: "TJ", region: 3 },
  { id: 195, name: "Tanzania", alpha: "TZ", region: 3 },
  { id: 94, name: "Thailand", alpha: "TH", region: 3 },
  { id: 196, name: "Timor Leste", alpha: "TL", region: 3 },
  { id: 93, name: "Togo", alpha: "TG", region: 3 },
  { id: 197, name: "Trinidad & Tobago", alpha: "TT", region: 3 },
  { id: 97, name: "Tunisia", alpha: "TN", region: 3 },
  { id: 98, name: "Turkey", alpha: "TR", region: 3 },
  { id: 96, name: "Turkmenistan", alpha: "TM", region: 3 },
  { id: 198, name: "Turks & Caicos Islands", alpha: "TC", region: 3 },
  { id: 100, name: "Uganda", alpha: "UG", region: 3 },
  { id: 99, name: "Ukraine", alpha: "UA", region: 3 },
  { id: 1, name: "United Arab Emirates", alpha: "AE", region: 3 },
  { id: 199, name: "United States of America (USA)", alpha: "US", region: 2 },
  { id: 101, name: "Uruguay", alpha: "UY", region: 3 },
  { id: 102, name: "Uzbekistan", alpha: "UZ", region: 3 },
  { id: 103, name: "Venezuela", alpha: "VE", region: 3 },
  { id: 106, name: "Vietnam", alpha: "VN", region: 3 },
  { id: 104, name: "Virgin Islands (UK)", alpha: "VG", region: 3 },
  { id: 105, name: "Virgin Islands (US)", alpha: "VI", region: 3 },
  { id: 108, name: "Yemen", alpha: "YE", region: 3 },
  { id: 111, name: "Zambia", alpha: "ZM", region: 3 },
  { id: 112, name: "Zimbabwe", alpha: "ZW", region: 3 },
];

const byId = new Map(ALLIANZ_COUNTRIES.map((c) => [c.id, c]));
const byName = new Map(ALLIANZ_COUNTRIES.map((c) => [c.name.trim().toLowerCase(), c]));

export function allianzCountryById(id: number): AllianzCountry | undefined {
  return byId.get(id);
}

export function allianzCountryByName(name: string): AllianzCountry | undefined {
  return byName.get(name.trim().toLowerCase());
}
