/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as MyRequestsRouteImport } from './routes/my-requests'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StartRequestRouteImport } from './routes/start-request'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDestinationsRouteImport } from './routes/admin.destinations'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServicesContentRouteImport } from './routes/admin.services-content'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as BookingConfirmationRequestIdRouteImport } from './routes/booking-confirmation.$requestId'
import { Route as BookingReviewRequestIdRouteImport } from './routes/booking-review.$requestId'
import { Route as CheckoutRequestIdRouteImport } from './routes/checkout.$requestId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as PassengersRequestIdRouteImport } from './routes/passengers.$requestId'
import { Route as PaymentRequestIdRouteImport } from './routes/payment.$requestId'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin.requests.index'
import { Route as AdminRequestsIdRouteImport } from './routes/admin.requests.$id'
import { Route as ApiPublicPaymentsPaystackWebhookRouteImport } from './routes/api/public/payments/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRequestsRoute = MyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRequestRoute = StartRequestRouteImport.update({
  id: '/start-request',
  path: '/start-request',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/admin/destinations',
  path: '/admin/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesContentRoute = AdminServicesContentRouteImport.update({
  id: '/admin/services-content',
  path: '/admin/services-content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRequestIdRoute =
  BookingConfirmationRequestIdRouteImport.update({
    id: '/booking-confirmation/$requestId',
    path: '/booking-confirmation/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingReviewRequestIdRoute = BookingReviewRequestIdRouteImport.update({
  id: '/booking-review/$requestId',
  path: '/booking-review/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRequestIdRoute = CheckoutRequestIdRouteImport.update({
  id: '/checkout/$requestId',
  path: '/checkout/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/dashboard/payments',
  path: '/dashboard/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengersRequestIdRoute = PassengersRequestIdRouteImport.update({
  id: '/passengers/$requestId',
  path: '/passengers/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRequestIdRoute = PaymentRequestIdRouteImport.update({
  id: '/payment/$requestId',
  path: '/payment/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/admin/requests/',
  path: '/admin/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsIdRoute = AdminRequestsIdRouteImport.update({
  id: '/admin/requests/$id',
  path: '/admin/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsPaystackWebhookRoute =
  ApiPublicPaymentsPaystackWebhookRouteImport.update({
    id: '/api/public/payments/paystack/webhook',
    path: '/api/public/payments/paystack/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/documents': typeof DocumentsRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/my-requests': typeof MyRequestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start-request': typeof StartRequestRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/services-content': typeof AdminServicesContentRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/booking-confirmation/$requestId': typeof BookingConfirmationRequestIdRoute
  '/booking-review/$requestId': typeof BookingReviewRequestIdRoute
  '/checkout/$requestId': typeof CheckoutRequestIdRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/passengers/$requestId': typeof PassengersRequestIdRoute
  '/payment/$requestId': typeof PaymentRequestIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/api/public/payments/paystack/webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/documents': typeof DocumentsRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/my-requests': typeof MyRequestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start-request': typeof StartRequestRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/services-content': typeof AdminServicesContentRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/booking-confirmation/$requestId': typeof BookingConfirmationRequestIdRoute
  '/booking-review/$requestId': typeof BookingReviewRequestIdRoute
  '/checkout/$requestId': typeof CheckoutRequestIdRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/passengers/$requestId': typeof PassengersRequestIdRoute
  '/payment/$requestId': typeof PaymentRequestIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/api/public/payments/paystack/webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/documents': typeof DocumentsRoute
  '/flights': typeof FlightsRoute
  '/hotels': typeof HotelsRoute
  '/my-requests': typeof MyRequestsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/start-request': typeof StartRequestRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/services-content': typeof AdminServicesContentRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/booking-confirmation/$requestId': typeof BookingConfirmationRequestIdRoute
  '/booking-review/$requestId': typeof BookingReviewRequestIdRoute
  '/checkout/$requestId': typeof CheckoutRequestIdRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/passengers/$requestId': typeof PassengersRequestIdRoute
  '/payment/$requestId': typeof PaymentRequestIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/requests/$id': typeof AdminRequestsIdRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/api/public/payments/paystack/webhook': typeof ApiPublicPaymentsPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/documents'
    | '/flights'
    | '/hotels'
    | '/my-requests'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/request'
    | '/reset-password'
    | '/start-request'
    | '/terms'
    | '/track'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/destinations'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/services'
    | '/admin/services-content'
    | '/admin/testimonials'
    | '/booking-confirmation/$requestId'
    | '/booking-review/$requestId'
    | '/checkout/$requestId'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/passengers/$requestId'
    | '/payment/$requestId'
    | '/requests/$id'
    | '/services/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/services/'
    | '/admin/requests/$id'
    | '/admin/requests/'
    | '/api/public/payments/paystack/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/documents'
    | '/flights'
    | '/hotels'
    | '/my-requests'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/request'
    | '/reset-password'
    | '/start-request'
    | '/terms'
    | '/track'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/destinations'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/services'
    | '/admin/services-content'
    | '/admin/testimonials'
    | '/booking-confirmation/$requestId'
    | '/booking-review/$requestId'
    | '/checkout/$requestId'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/passengers/$requestId'
    | '/payment/$requestId'
    | '/requests/$id'
    | '/services/$slug'
    | '/admin'
    | '/dashboard'
    | '/services'
    | '/admin/requests/$id'
    | '/admin/requests'
    | '/api/public/payments/paystack/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/documents'
    | '/flights'
    | '/hotels'
    | '/my-requests'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/request'
    | '/reset-password'
    | '/start-request'
    | '/terms'
    | '/track'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/destinations'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/services'
    | '/admin/services-content'
    | '/admin/testimonials'
    | '/booking-confirmation/$requestId'
    | '/booking-review/$requestId'
    | '/checkout/$requestId'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/passengers/$requestId'
    | '/payment/$requestId'
    | '/requests/$id'
    | '/services/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/services/'
    | '/admin/requests/$id'
    | '/admin/requests/'
    | '/api/public/payments/paystack/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DocumentsRoute: typeof DocumentsRoute
  FlightsRoute: typeof FlightsRoute
  HotelsRoute: typeof HotelsRoute
  MyRequestsRoute: typeof MyRequestsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StartRequestRoute: typeof StartRequestRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminServicesContentRoute: typeof AdminServicesContentRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  BookingConfirmationRequestIdRoute: typeof BookingConfirmationRequestIdRoute
  BookingReviewRequestIdRoute: typeof BookingReviewRequestIdRoute
  CheckoutRequestIdRoute: typeof CheckoutRequestIdRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  PassengersRequestIdRoute: typeof PassengersRequestIdRoute
  PaymentRequestIdRoute: typeof PaymentRequestIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  AdminRequestsIdRoute: typeof AdminRequestsIdRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  ApiPublicPaymentsPaystackWebhookRoute: typeof ApiPublicPaymentsPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-requests': {
      id: '/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof MyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-request': {
      id: '/start-request'
      path: '/start-request'
      fullPath: '/start-request'
      preLoaderRoute: typeof StartRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/admin/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services-content': {
      id: '/admin/services-content'
      path: '/admin/services-content'
      fullPath: '/admin/services-content'
      preLoaderRoute: typeof AdminServicesContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation/$requestId': {
      id: '/booking-confirmation/$requestId'
      path: '/booking-confirmation/$requestId'
      fullPath: '/booking-confirmation/$requestId'
      preLoaderRoute: typeof BookingConfirmationRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-review/$requestId': {
      id: '/booking-review/$requestId'
      path: '/booking-review/$requestId'
      fullPath: '/booking-review/$requestId'
      preLoaderRoute: typeof BookingReviewRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$requestId': {
      id: '/checkout/$requestId'
      path: '/checkout/$requestId'
      fullPath: '/checkout/$requestId'
      preLoaderRoute: typeof CheckoutRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/dashboard/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passengers/$requestId': {
      id: '/passengers/$requestId'
      path: '/passengers/$requestId'
      fullPath: '/passengers/$requestId'
      preLoaderRoute: typeof PassengersRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$requestId': {
      id: '/payment/$requestId'
      path: '/payment/$requestId'
      fullPath: '/payment/$requestId'
      preLoaderRoute: typeof PaymentRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/admin/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/$id': {
      id: '/admin/requests/$id'
      path: '/admin/requests/$id'
      fullPath: '/admin/requests/$id'
      preLoaderRoute: typeof AdminRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/paystack/webhook': {
      id: '/api/public/payments/paystack/webhook'
      path: '/api/public/payments/paystack/webhook'
      fullPath: '/api/public/payments/paystack/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  DocumentsRoute: DocumentsRoute,
  FlightsRoute: FlightsRoute,
  HotelsRoute: HotelsRoute,
  MyRequestsRoute: MyRequestsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StartRequestRoute: StartRequestRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminServicesContentRoute: AdminServicesContentRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  BookingConfirmationRequestIdRoute: BookingConfirmationRequestIdRoute,
  BookingReviewRequestIdRoute: BookingReviewRequestIdRoute,
  CheckoutRequestIdRoute: CheckoutRequestIdRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  PassengersRequestIdRoute: PassengersRequestIdRoute,
  PaymentRequestIdRoute: PaymentRequestIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  AdminRequestsIdRoute: AdminRequestsIdRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  ApiPublicPaymentsPaystackWebhookRoute: ApiPublicPaymentsPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
