// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etfvjtyrsmcsawsdxqgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0ZnZqdHlyc21jc2F3c2R4cWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0NDU0OTYsImV4cCI6MjEwMTAyMTQ5Nn0.5sTuHu8i6a2EtjrmEVX2PtkVIfjMKdFFP6jLiPoHvhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});