// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awkmtrkkdxsxqxjquewr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3a210cmtrZHhzeHF4anF1ZXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0NjcxNTksImV4cCI6MjEwMTA0MzE1OX0.SRx4hXc3VYkxYwbycsrEMNZQ-M8c05I6Dz3j6X3IyvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});